### ISSUE TITLE
[REQUEST] No longer iterate through all possible items in indexes

### ISSUE THREAD

**Issue by mingl0280** [Progeny42/refrapt#12]
This is due to too many web requests and some of them got rejected caused by index download iteration. 
Suggestion: when downloading the indexes, you should:

- For non-flat repository:
1. parse the InRelease file (which included all possible index files).
2. Download the index files only present in the InRelease file. 

- For flat repository:
Not needed to parse the InRelease file. 

https://wiki.debian.org/DebianRepository/Format This webpage included the deb tree definition.

**Comment by Progeny42** [comment]
I have had a go at making this change. Taking a look at the Debian Repository format, it states that "If indexes are compressed, checksum data must be provided for uncompressed files as well, even if not present on the server."; This means that there are still likely to be some false positives, but it should lessen the amount, and takes out the guesswork that was previously implemented. For example, I've gone from 1100 Index files down to 715 using this method.

I'm doing some additional testing first, but should pull the changes in soon.

**Comment by mingl0280** [comment]
> 

The key issue is that successful queries wouldn't be considered attacks normally, but failed ones can.

**Comment by Progeny42** [comment]
I've just pulled in the changes from #13, which have gone into release v0.3.1. Depending on your mirrors, this should help reduce unsuccessful queries.

Regardless, it has helped reduce a lot of code not-so-nice code, so it's of benefit to the project.
