### ISSUE TITLE
[BUG] Missing translation files, when OS has a diffrent language than the mirror server

### ISSUE THREAD

**Issue by merlin1234** [Progeny42/refrapt#16]
The translations files are not pulled from the source mirror, when the OS, connected to the refrapt mirror has a different language used (e.g refrapt Server Language / Locale EN_US, Server DE_DE)

Here the message from a Server (doing apt update from the refrapt mirror) - unfortunate in German:

 E: Fehlschlag beim Holen von http://REFRAPT_IP/debian/dists/stretch/main/i18n/Translation-de_DE  404  Not Found
(E: Error getting from http://REFRAPT_IP/debian/dists/stretch/main/i18n/Translation-de_DE  404  Not Found)

This will lead apt to cancel the update from this mirror, as it does not find all Index files. 

Its something between a feature and a bug - An options for translation download would be necessary here to get out of this, where the User can specify which languages he is using on his machine.  Default could be the refrapts servers  language ( config like with default_architecture)

Sources are not depending on Ubuntu / Debian - I think this thing will occur with every .deb based distribution. 

**System Information:**
 - OS: Debian 11
 - Refrapt Version  0.3.3

**Comment by Progeny42** [comment]
I hadn't anticipated that clients of the Refrapt mirror may not be of the same Locale. I've added support for multiple Languages for the Translation indexes via the Configuration file in v0.3.4. 

Install the latest version of Refrapt, and then modify your `refrapt.conf` configuration file like so:
`set language = en_US, de_DE`

This will instruct Refrapt to download Translation indexes for each Language code.

**Comment by merlin1234** [comment]
Great job, works fine - we can close this
