### ISSUE TITLE
[BUG] Progress causes crash and implemented incorrectly

### ISSUE THREAD

**Issue by tiix95** [Progeny42/refrapt#40]
Hi,
After your release v0.4.8, I tested again in my setup and spotted two bugs : 
```
$ refrapt --conf /tmp/debian-light.conf 
Traceback (most recent call last):
  File "/usr/local/bin/refrapt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: main() got an unexpected keyword argument 'no_progress'
````
I think this is due to the variable name in click.option not the same as main() function arg. I fixed just like this :

```
$ diff upstream_refrapt/refrapt.py local_refrapt/refrapt.py 
44c44
< def main(conf: str, test: bool, clean: bool, noProgress: bool):
---
> def main(conf: str, test: bool, clean: bool, no_progress: bool):
72c72
<     if noProgress:
---
>     if no_progress:
```

The second bug is directly related to the disableProgress option. Using your release as-is (and after fixing above bug), progress bars are still there, no matter if I use command line or config file option.
In my comprehension, your new function ProgressBarsEnabled() should return True if the option is enabled, and the `disable` option in tqdm should be set with this value. So why did you set all `disable` options to `not Settings.ProgressBarsEnabled()` ?
I tested with `disable=Settings.ProgressBarsEnabled()` and it correctly removes the progress bars.

Please let me know if I can help more

Thanks

**Comment by Progeny42** [comment]
Ah, I see. The constructor is easily fixed.

The issue with the no progress setting is because the `ProgressBarsEnabled()` should have been an inverse check. I will fix both and push a new release shortly.

**Comment by Progeny42** [comment]
I've just pushed v0.4.9 which should address both issues. I've checked locally that both the command line and configuration file options work correctly.

**Comment by tiix95** [comment]
I just tested in my setup and as far I can see it's working as expected.

Thank you !
