### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement refrapt

### ISSUE THREAD

**Issue by Maks1116** [Progeny42/refrapt#6]
When I run `pip3 install refrapt` to install refrapt I get this error:
```
$ pip3 install refrapt
ERROR: Could not find a version that satisfies the requirement refrapt (from versions: none)
ERROR: No matching distribution found for refrapt
```
Same thing happens when I run it with root privilleges.

**Comment by Progeny42** [comment]
This likely means you are running the wrong version of Python - you require Version 3.9. You can verify this by running `pip3 install refrapt --verbose`, and you should see output along the lines of `Link requires a different Python (X.X.X not in '>3.9'...`.

Ensure you have at least `python3.9` installed:
`sudo apt-get install python3.9`

and then try the following command to install explicitly using `python3.9`:
`python3.9 -m pip install refrapt`

I shall update the documentation to use the above command, as it will more easily identify if people don't have the correct version of Python installed.

**Comment by Maks1116** [comment]
Thank you for your help. I can install it with python3.9.
