### ISSUE TITLE
[BUG] Refrapt uses python3 instead of python3.9

### ISSUE THREAD

**Issue by Maks1116** [Progeny42/refrapt#7]
**Describe the bug**
When running refrapt command I get:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/refrapt", line 5, in <module>
    from refrapt.refrapt import main
ModuleNotFoundError: No module named 'refrapt'
```
I have fixed this by changing
```
#!/usr/bin/python3
```
to
```
#!/usr/bin/python3.9
```
in `~/.local/bin/refrapt`

**System Information:**
 - OS: Ubuntu Server 20.04 (on raspberry pi 4b+)
 - Refrapt Version 0.2.0

**Comment by Progeny42** [comment]
I've checked my installation, in the `~/.local/bin/refrapt` file, and it already has `#!/usr/bin/python3.9`. I can only assume therefore yours was set to `python3` due to the previous installation attempt for which you were having trouble with in issue #6.

**Comment by Maks1116** [comment]
It doesn't happen now so I will close this issue
